using AkyuiUnity.Editor.ScriptableObject;
using AkyuiUnity.Loader;
using UnityEngine;
using UnityEngine.UI;

namespace AkyuiUnity.Xd.Extensions
{
    [CreateAssetMenu(menuName = "AkyuiXd/Triggers/RemoveAutoGeneratedMaskTrigger", fileName = nameof(RemoveAutoGeneratedMaskTrigger))]
    public class RemoveAutoGeneratedMaskTrigger : AkyuiImportTrigger
    {
        public override void OnPostprocessPrefab(IAkyuiLoader loader, ref GameObject prefab)
        {
            foreach (var mask in prefab.GetComponentsInChildren<Mask>(true))
            {
                var gameObject = mask.gameObject;
                if (gameObject.transform.childCount == 1 && gameObject.transform.GetChild(0).name == "Inner Image")
                {
                    DestroyImmediate(gameObject.GetComponent<Mask>());
                    DestroyImmediate(gameObject.GetComponent<Image>());
                }
            }
        }
    }
}
